### ISSUE TITLE
error: Uncaught TypeError: Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by longrunningprocess** [lucacasonato/deno_s3#28]
I was just trying to run a simple `bucket.listAllObjects` and saw this error:

```javascript
error: Uncaught TypeError: Cannot read property 'byteLength' of undefined
  const paddedKey: Uint8Array = new Uint8Array(4 + key.byteLength);
                                                       ^
    at getSignatureKey (https://deno.land/x/aws_sign_v4@1.0.1/src/signing.ts:34:56)

```

I had noticed a similar issue (or same possibly) in my little attempt as well, I do it a little differently:

```javascript
import { S3Client, ListObjectsV2Command } from 'https://cdn.skypack.dev/@aws-sdk/client-s3'

const client = new S3Client({
	region: 'us-east-1',
	credentials: {
		AccessKeyId: config.AWS_ACCESS_KEY_ID,
		SecretAccessKey: config.AWS_SECRET_ACCESS_KEY,
	}
})

async function list() {
s3/interfaces/listobjectsv2commandinput.html
	const objs = await client.send(new ListObjectsV2Command({
		Bucket: 'my-bucket'
	}))

	console.log(objs)
}

list()
```

again seeing this:
```javascript
error: Uncaught (in promise) TypeError: Cannot read property 'byteLength' of undefined
    return data.byteLength === 0;
                ^
    at isEmptyData (https://cdn.skypack.dev/-/@aws-crypto/sha256-js@v1.1.0-dHYF8d6vKNrHMAy8OSBp/dist=es2020,mode=imports/optimized/@aws-crypto/sha256-js.js:273:17)

```

I realize you all may have abandoned this mod but wanted to take the chance you all may have some insight.

Thanks!

**Comment by longrunningprocess** [comment]
I was simply using the wrong set of property names, this ended up working (camelCase):

```javascript
const client = new S3Client({
	region: 'us-east-1',
	credentials: {
		accessKeyId: config.AWS_ACCESS_KEY_ID,
		secretAccessKey: config.AWS_SECRET_ACCESS_KEY,
	}
})
```
